package lk.epicgreen.erp.report.entity;

import jakarta.persistence.*;
import lk.epicgreen.erp.common.audit.AuditEntity;
import lombok.*;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * SavedReport entity
 * Represents saved reports and report templates
 * 
 * @author Epic Green Development Team
 * @version 1.0
 */
@Entity
@Table(name = "saved_reports", indexes = {
    @Index(name = "idx_saved_report_code", columnList = "report_code"),
    @Index(name = "idx_saved_report_type", columnList = "report_type"),
    @Index(name = "idx_saved_report_category", columnList = "report_category"),
    @Index(name = "idx_saved_report_user", columnList = "created_by_user_id"),
    @Index(name = "idx_saved_report_status", columnList = "status")
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class SavedReport extends AuditEntity {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    /**
     * Report code (unique identifier)
     */
    @Column(name = "report_code", nullable = false, unique = true, length = 50)
    private String reportCode;
    
    /**
     * Report name
     */
    @Column(name = "report_name", nullable = false, length = 200)
    private String reportName;
    
    /**
     * Report type (SALES, PURCHASE, INVENTORY, FINANCIAL, PRODUCTION, CUSTOMER, SUPPLIER, CUSTOM)
     */
    @Column(name = "report_type", nullable = false, length = 30)
    private String reportType;
    
    /**
     * Report category (OPERATIONAL, ANALYTICAL, STATUTORY, MANAGEMENT, DASHBOARD)
     */
    @Column(name = "report_category", length = 30)
    private String reportCategory;
    
    /**
     * Report format (PDF, EXCEL, CSV, JSON, HTML)
     */
    @Column(name = "report_format", length = 20)
    private String reportFormat;
    
    /**
     * Is template (can be used as template for creating new reports)
     */
    @Column(name = "is_template")
    private Boolean isTemplate;
    
    /**
     * Is system report (built-in, cannot be deleted)
     */
    @Column(name = "is_system")
    private Boolean isSystem;
    
    /**
     * Is public (visible to all users)
     */
    @Column(name = "is_public")
    private Boolean isPublic;
    
    /**
     * Created by user ID
     */
    @Column(name = "created_by_user_id")
    private Long createdByUserId;
    
    /**
     * Created by username
     */
    @Column(name = "created_by_username", length = 50)
    private String createdByUsername;
    
    /**
     * Description
     */
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;
    
    /**
     * Report query (SQL query for data retrieval)
     */
    @Column(name = "report_query", columnDefinition = "TEXT")
    private String reportQuery;
    
    /**
     * Report parameters (JSON - parameter definitions)
     */
    @Column(name = "report_parameters", columnDefinition = "TEXT")
    private String reportParameters;
    
    /**
     * Report filters (JSON - filter definitions)
     */
    @Column(name = "report_filters", columnDefinition = "TEXT")
    private String reportFilters;
    
    /**
     * Report columns (JSON - column definitions)
     */
    @Column(name = "report_columns", columnDefinition = "TEXT")
    private String reportColumns;
    
    /**
     * Report layout (JSON - layout configuration)
     */
    @Column(name = "report_layout", columnDefinition = "TEXT")
    private String reportLayout;
    
    /**
     * Report styling (JSON - styling configuration)
     */
    @Column(name = "report_styling", columnDefinition = "TEXT")
    private String reportStyling;
    
    /**
     * Data source (DATABASE, API, FILE, CUSTOM)
     */
    @Column(name = "data_source", length = 20)
    private String dataSource;
    
    /**
     * Data source connection (connection string or config)
     */
    @Column(name = "data_source_connection", columnDefinition = "TEXT")
    private String dataSourceConnection;
    
    /**
     * Schedule enabled (can be scheduled for automatic generation)
     */
    @Column(name = "schedule_enabled")
    private Boolean scheduleEnabled;
    
    /**
     * Schedule cron expression (for scheduled reports)
     */
    @Column(name = "schedule_cron", length = 100)
    private String scheduleCron;
    
    /**
     * Schedule recipients (comma-separated email addresses)
     */
    @Column(name = "schedule_recipients", columnDefinition = "TEXT")
    private String scheduleRecipients;
    
    /**
     * Last generated at
     */
    @Column(name = "last_generated_at")
    private LocalDateTime lastGeneratedAt;
    
    /**
     * Last generated by
     */
    @Column(name = "last_generated_by", length = 50)
    private String lastGeneratedBy;
    
    /**
     * Generation count
     */
    @Column(name = "generation_count")
    private Integer generationCount;
    
    /**
     * Status (ACTIVE, INACTIVE, ARCHIVED)
     */
    @Column(name = "status", length = 20)
    private String status;
    
    /**
     * Tags (comma-separated tags for categorization)
     */
    @Column(name = "tags", length = 500)
    private String tags;
    
    /**
     * Notes
     */
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;
    
    /**
     * File path (if report is stored as file)
     */
    @Column(name = "file_path", length = 500)
    private String filePath;
    
    /**
     * File size in bytes
     */
    @Column(name = "file_size_bytes")
    private Long fileSizeBytes;
    
    /**
     * Average generation time in milliseconds
     */
    @Column(name = "avg_generation_time_millis")
    private Long avgGenerationTimeMillis;

    // ==================== NEW FIELDS FOR SERVICE LAYER ====================
    
    /**
     * Format (alias for reportFormat)
     */
    @Column(name = "format", length = 20)
    private String format;
    
    /**
     * Category (alias for reportCategory)
     */
    @Column(name = "category", length = 50)
    private String category;
    
    /**
     * Start date for report period
     */
    @Column(name = "start_date")
    private LocalDate startDate;
    
    /**
     * End date for report period
     */
    @Column(name = "end_date")
    private LocalDate endDate;
    
    /**
     * Generation time in milliseconds (for last generation)
     */
    @Column(name = "generation_time_millis")
    private Long generationTimeMillis;
    
    /**
     * Record count (number of records in last generated report)
     */
    @Column(name = "record_count")
    private Integer recordCount;
    
    /**
     * Error message (if report generation failed)
     */
    @Column(name = "error_message", columnDefinition = "TEXT")
    private String errorMessage;

    // ==================== HELPER METHODS ====================
    
    /**
     * Gets format (format or reportFormat)
     */
    public String getFormat() {
        return format != null ? format : reportFormat;
    }
    
    /**
     * Gets category (category or reportCategory)
     */
    public String getCategory() {
        return category != null ? category : reportCategory;
    }
    
    /**
     * Gets start date
     */
    public LocalDate getStartDate() {
        return startDate;
    }
    
    /**
     * Gets end date
     */
    public LocalDate getEndDate() {
        return endDate;
    }
    
    /**
     * Gets generation time in milliseconds
     */
    public Long getGenerationTimeMillis() {
        return generationTimeMillis;
    }
    
    /**
     * Sets generation time in milliseconds (from long)
     */
    public void setGenerationTimeMillis(long generationTimeMillis) {
        this.generationTimeMillis = generationTimeMillis;
    }
    
    /**
     * Sets generation time in milliseconds (from Long)
     */
    public void setGenerationTimeMillis(Long generationTimeMillis) {
        this.generationTimeMillis = generationTimeMillis;
    }
    
    /**
     * Gets record count
     */
    public Integer getRecordCount() {
        return recordCount;
    }
    
    /**
     * Sets record count (from int)
     */
    public void setRecordCount(int recordCount) {
        this.recordCount = recordCount;
    }
    
    /**
     * Sets record count (from Integer)
     */
    public void setRecordCount(Integer recordCount) {
        this.recordCount = recordCount;
    }
    
    /**
     * Gets error message
     */
    public String getErrorMessage() {
        return errorMessage;
    }
    
    /**
     * Sets error message
     */
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }
    
    // ==================== EXISTING METHODS ====================
    
    /**
     * Checks if is active
     */
    @Transient
    public boolean isActive() {
        return "ACTIVE".equals(status);
    }
    
    /**
     * Checks if is archived
     */
    @Transient
    public boolean isArchived() {
        return "ARCHIVED".equals(status);
    }
    
    /**
     * Checks if can be deleted
     */
    @Transient
    public boolean canDelete() {
        return !isSystem;
    }
    
    /**
     * Checks if can be edited
     */
    @Transient
    public boolean canEdit() {
        return !isSystem || isActive();
    }
    
    /**
     * Checks if is scheduled
     */
    @Transient
    public boolean isScheduled() {
        return scheduleEnabled != null && scheduleEnabled && scheduleCron != null;
    }
    
    /**
     * Gets file size in KB
     */
    @Transient
    public Double getFileSizeKB() {
        if (fileSizeBytes == null) {
            return 0.0;
        }
        return fileSizeBytes / 1024.0;
    }
    
    /**
     * Gets file size in MB
     */
    @Transient
    public Double getFileSizeMB() {
        if (fileSizeBytes == null) {
            return 0.0;
        }
        return fileSizeBytes / (1024.0 * 1024.0);
    }
    
    /**
     * Gets average generation time in seconds
     */
    @Transient
    public Double getAvgGenerationTimeSeconds() {
        if (avgGenerationTimeMillis == null) {
            return 0.0;
        }
        return avgGenerationTimeMillis / 1000.0;
    }
    
    /**
     * Gets days since last generation
     */
    @Transient
    public Long getDaysSinceLastGeneration() {
        if (lastGeneratedAt == null) {
            return null;
        }
        return java.time.temporal.ChronoUnit.DAYS.between(
                lastGeneratedAt.toLocalDate(),
                LocalDateTime.now().toLocalDate()
        );
    }
    
    @PrePersist
    protected void onCreate() {
        super.onCreate();
        if (status == null) {
            status = "ACTIVE";
        }
        if (isTemplate == null) {
            isTemplate = false;
        }
        if (isSystem == null) {
            isSystem = false;
        }
        if (isPublic == null) {
            isPublic = false;
        }
        if (scheduleEnabled == null) {
            scheduleEnabled = false;
        }
        if (generationCount == null) {
            generationCount = 0;
        }
        if (dataSource == null) {
            dataSource = "DATABASE";
        }
        if (reportFormat == null) {
            reportFormat = "PDF";
        }
        // Sync format and category
        if (format == null && reportFormat != null) {
            format = reportFormat;
        }
        if (category == null && reportCategory != null) {
            category = reportCategory;
        }
    }
    
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SavedReport)) return false;
        SavedReport that = (SavedReport) o;
        return id != null && id.equals(that.getId());
    }
    
    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
