package lk.epicgreen.erp.accounting.repository;

import lk.epicgreen.erp.accounting.entity.TrialBalance;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

/**
 * Repository interface for TrialBalance entity
 * Based on ACTUAL database schema: trial_balance table
 * 
 * Fields: period_id (BIGINT), account_id (BIGINT),
 *         opening_debit, opening_credit, period_debit, period_credit,
 *         closing_debit, closing_credit,
 *         generated_at, generated_by (BIGINT)
 * 
 * NOTE: Unique constraint on (period_id, account_id)
 * 
 * @author Epic Green Development Team
 * @version 1.0
 */
@Repository
public interface TrialBalanceRepository extends JpaRepository<TrialBalance, Long>, JpaSpecificationExecutor<TrialBalance> {
    
    // ==================== FINDER METHODS ====================
    
    /**
     * Find trial balance by period and account
     */
    Optional<TrialBalance> findByPeriodIdAndAccountId(Long periodId, Long accountId);
    
    /**
     * Find all trial balance entries for a period
     */
    List<TrialBalance> findByPeriodId(Long periodId);
    
    /**
     * Find all trial balance entries for a period with pagination
     */
    Page<TrialBalance> findByPeriodId(Long periodId, Pageable pageable);
    
    /**
     * Find all trial balance entries for a period ordered by account
     */
    @Query("SELECT tb FROM TrialBalance tb WHERE tb.period.id = :periodId ORDER BY tb.account.id")
    List<TrialBalance> findByPeriodOrderByAccount(@Param("periodId") Long periodId);
    
    /**
     * Find all trial balance entries for an account
     */
    List<TrialBalance> findByAccountId(Long accountId);
    
    /**
     * Find trial balance entries generated by user
     */
    List<TrialBalance> findByGeneratedBy(Long generatedBy);
    
    // ==================== EXISTENCE CHECKS ====================
    
    /**
     * Check if trial balance exists for period and account
     */
    boolean existsByPeriodIdAndAccountId(Long periodId, Long accountId);
    
    // ==================== COUNT METHODS ====================
    
    /**
     * Count trial balance entries for a period
     */
    long countByPeriodId(Long periodId);
    
    /**
     * Count trial balance entries for an account
     */
    long countByAccountId(Long accountId);
    
    // ==================== DELETE METHODS ====================
    
    /**
     * Delete all trial balance entries for a period
     */
    @Modifying
    @Query("DELETE FROM TrialBalance tb WHERE tb.period.id = :periodId")
    void deleteAllByPeriodId(@Param("periodId") Long periodId);
    
    // ==================== CUSTOM QUERIES ====================
    
    /**
     * Get total opening debit for period
     */
    @Query("SELECT SUM(tb.openingDebit) FROM TrialBalance tb WHERE tb.period.id = :periodId")
    BigDecimal getTotalOpeningDebitByPeriod(@Param("periodId") Long periodId);
    
    /**
     * Get total opening credit for period
     */
    @Query("SELECT SUM(tb.openingCredit) FROM TrialBalance tb WHERE tb.period.id = :periodId")
    BigDecimal getTotalOpeningCreditByPeriod(@Param("periodId") Long periodId);
    
    /**
     * Get total period debit for period
     */
    @Query("SELECT SUM(tb.periodDebit) FROM TrialBalance tb WHERE tb.period.id = :periodId")
    BigDecimal getTotalPeriodDebitByPeriod(@Param("periodId") Long periodId);
    
    /**
     * Get total period credit for period
     */
    @Query("SELECT SUM(tb.periodCredit) FROM TrialBalance tb WHERE tb.period.id = :periodId")
    BigDecimal getTotalPeriodCreditByPeriod(@Param("periodId") Long periodId);
    
    /**
     * Get total closing debit for period
     */
    @Query("SELECT SUM(tb.closingDebit) FROM TrialBalance tb WHERE tb.period.id = :periodId")
    BigDecimal getTotalClosingDebitByPeriod(@Param("periodId") Long periodId);
    
    /**
     * Get total closing credit for period
     */
    @Query("SELECT SUM(tb.closingCredit) FROM TrialBalance tb WHERE tb.period.id = :periodId")
    BigDecimal getTotalClosingCreditByPeriod(@Param("periodId") Long periodId);
    
    /**
     * Find trial balance entries with activity (period debit or credit > 0)
     */
    @Query("SELECT tb FROM TrialBalance tb WHERE tb.period.id = :periodId " +
           "AND (tb.periodDebit > 0 OR tb.periodCredit > 0) ORDER BY tb.account.id")
    List<TrialBalance> findActiveEntriesByPeriod(@Param("periodId") Long periodId);
    
    /**
     * Find trial balance entries generated in time range
     */
    @Query("SELECT tb FROM TrialBalance tb WHERE tb.generatedAt BETWEEN :startTime AND :endTime " +
           "ORDER BY tb.generatedAt DESC")
    List<TrialBalance> findEntriesGeneratedBetween(
            @Param("startTime") LocalDateTime startTime,
            @Param("endTime") LocalDateTime endTime);
    
    /**
     * Get trial balance statistics for period
     */
    @Query("SELECT " +
           "COUNT(tb) as totalAccounts, " +
           "SUM(tb.openingDebit) as totalOpeningDebit, " +
           "SUM(tb.openingCredit) as totalOpeningCredit, " +
           "SUM(tb.periodDebit) as totalPeriodDebit, " +
           "SUM(tb.periodCredit) as totalPeriodCredit, " +
           "SUM(tb.closingDebit) as totalClosingDebit, " +
           "SUM(tb.closingCredit) as totalClosingCredit " +
           "FROM TrialBalance tb WHERE tb.period.id = :periodId")
    Object getTrialBalanceStatistics(@Param("periodId") Long periodId);
    
    /**
     * Find all trial balance entries ordered by period
     */
    @Query("SELECT tb FROM TrialBalance tb ORDER BY tb.period.id, tb.account.id")
    List<TrialBalance> findAllOrderedByPeriod();
}
